name = "atologs"
main = "src/index.ts"
compatibility_date = "2024-12-30"
workers_dev = true

[[routes]]
pattern = "atologs.com"
custom_domain = true

[assets]
directory = "./public"

[[rules]]
type = "Data"
globs = ["**/*.ttf"]

[[kv_namespaces]]
binding = "KV"
id = "04971595d04a4696b96b1b2d52815532"
